#!/usr/bin/env python3
"""Regenerate tests/crypto_const_cases.c from the derivations in ghidra_api.

The fixture exists to prove that const_scan_utils recognises one constant
through several in-memory encodings, so the same value is emitted more than
once at different widths, byte orders and word orders. Deriving it from the
same code the scanner uses would be circular if the derivations were not
themselves checked -- test_crypto_const_utils.py checks them against the
structural properties each constant must have.

    python3 tests/gen_crypto_const_cases.py

Run from the repository root. Needs no Ghidra: crypto_const_utils is plain
integer arithmetic.
"""

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
OUTPUT = os.path.join(REPO, "tests", "crypto_const_cases.c")

from ghidra_api import crypto_const_utils as cc  # noqa: E402

HEADER = """/*
 * Crypto-constant fixture for the ghidra_api test suite.
 *
 * GENERATED by tests/gen_crypto_const_cases.py -- edit that, not this. Every
 * table here is laid out deliberately: the point is to check that
 * const_scan_utils recognises the same constant through different in-memory
 * encodings, so the same value appears more than once at different widths,
 * byte orders and word orders.
 *
 * These are file-scope globals with external linkage, so the compiler emits
 * them whether or not anything references them.
 */

#include <stdint.h>
"""


def rows(values, per_line, fmt):
    return "\n".join(
        "    " + " ".join(fmt % v for v in values[i:i + per_line])
        for i in range(0, len(values), per_line))


def table(ctype, name, values, per_line, fmt):
    return "const %s %s[%d] = {\n%s\n};\n" % (ctype, name, len(values),
                                                 rows(values, per_line, fmt))


def byteswap32(value):
    return (((value & 0x000000ff) << 24) | ((value & 0x0000ff00) << 8) |
            ((value & 0x00ff0000) >> 8) | ((value & 0xff000000) >> 24))


def build():
    parts = [HEADER]

    k256 = cc.sha2_round_constants(64, 32)
    parts.append("/* plain u32, native (little) endian */")
    parts.append(table("uint32_t", "fx_sha256_k_le", k256, 4, "0x%08xU,"))
    parts.append("/* the same table byte-swapped, so its bytes are big endian */")
    parts.append(table("uint32_t", "fx_sha256_k_be",
                       [byteswap32(v) for v in k256], 4, "0x%08xU,"))

    sbox = cc.aes_sbox()
    parts.append("/* byte table stored as bytes */")
    parts.append(table("uint8_t", "fx_aes_sbox_u8", sbox, 12, "0x%02x,"))
    parts.append("/* the same byte table widened to u32, as C int[] tables appear */")
    parts.append(table("uint32_t", "fx_aes_sbox_u32", sbox, 8, "0x%08xU,"))

    parts.append(table("uint32_t", "fx_crc32_table",
                       cc.crc_table(0xedb88320), 4, "0x%08xU,"))
    parts.append(table("uint32_t", "fx_md5_t", cc.md5_sine_table(), 4,
                       "0x%08xU,"))
    parts.append(table("uint32_t", "fx_blowfish_p", cc.pi_fraction_words(18),
                       4, "0x%08xU,"))
    parts.append(table("uint8_t", "fx_des_sboxes", cc.DES_SBOXES, 16, "0x%02x,"))

    iv512 = cc.sha2_64_state(0)
    parts.append(table("uint64_t", "fx_sha512_iv", iv512, 2, "0x%016xULL,"))
    swapped = []
    for value in iv512:
        swapped.append((value >> 32) & 0xffffffff)  # high half stored first ...
        swapped.append(value & 0xffffffff)          # ... each half little endian
    parts.append("/* u64 constants split into u32 halves, most significant first */")
    parts.append(table("uint32_t", "fx_sha512_iv_wordswapped", swapped, 4,
                       "0x%08xU,"))

    parts.append("/* bignum limbs stored least significant first */")
    parts.append(table("uint64_t", "fx_secp256k1_p_le",
                       list(reversed(cc.SECP256K1_P)), 2, "0x%016xULL,"))

    parts.append('const char fx_base64_alphabet[] =\n'
                 '    "ABCDEFGHIJKLMNOPQRSTUVWXYZ'
                 'abcdefghijklmnopqrstuvwxyz0123456789+/";\n')
    parts.append('const char fx_chacha_sigma[] = "expand 32-byte k";\n')
    return "\n".join(parts)


if __name__ == "__main__":
    with open(OUTPUT, "w") as handle:
        handle.write(build())
    print("wrote %s" % OUTPUT)
